name: test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.12
          - 1.13
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build & Test
      run: |
        make test
